// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacVBT95ObjMn2pkpSgzqoUcN6cuB47AM',
    appId: '1:82553153811:web:e4045e4439113b3aa612e6',
    messagingSenderId: '82553153811',
    projectId: 'socialapp-15324',
    authDomain: 'socialapp-15324.firebaseapp.com',
    storageBucket: 'socialapp-15324.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK4Tx8o-0xBTv7xCP_Q3spmLQeIx8pSdQ',
    appId: '1:82553153811:android:bb797abdcf04bae5a612e6',
    messagingSenderId: '82553153811',
    projectId: 'socialapp-15324',
    storageBucket: 'socialapp-15324.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYg2VPruQLvFXkerX3o8qb0qwJ8dzfK4',
    appId: '1:82553153811:ios:2ac91b162ac5f459a612e6',
    messagingSenderId: '82553153811',
    projectId: 'socialapp-15324',
    storageBucket: 'socialapp-15324.firebasestorage.app',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpYg2VPruQLvFXkerX3o8qb0qwJ8dzfK4',
    appId: '1:82553153811:ios:2ac91b162ac5f459a612e6',
    messagingSenderId: '82553153811',
    projectId: 'socialapp-15324',
    storageBucket: 'socialapp-15324.firebasestorage.app',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCacVBT95ObjMn2pkpSgzqoUcN6cuB47AM',
    appId: '1:82553153811:web:371d57155fb4d128a612e6',
    messagingSenderId: '82553153811',
    projectId: 'socialapp-15324',
    authDomain: 'socialapp-15324.firebaseapp.com',
    storageBucket: 'socialapp-15324.firebasestorage.app',
  );
}
